(() => {
"use strict";
const K={habits:"rotina-v1",settings:"rotina-settings-v1",profile:"rotina-profile-v1",notes:"rotina-notes-board-v1"};
const today=new Date();let month=new Date(today.getFullYear(),today.getMonth(),1),selectedDate=new Date(today),selectedHabitId=null,editingId=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const data=()=>read(K.habits,{habits:[]}),settings=()=>read(K.settings,{theme:"obsidian",motivation:true}),profile=()=>read(K.profile,{name:"Minha rotina",email:""});
const dateKey=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return y+"-"+m+"-"+day};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const norm=h=>({...h,frequency:h.frequency||"daily",days:Array.isArray(h.days)?h.days:[],weeklyTarget:Number(h.weeklyTarget)||3,category:h.category||"Rotina",time:h.time||"",goalValue:h.goalValue??"",goalUnit:h.goalUnit||"vez",completions:h.completions||{}});
const freq=h=>{h=norm(h);return h.frequency==="specific"?(h.days.length?"Dias: "+h.days.map(d=>["","Seg","Ter","Qua","Qui","Sex","Sáb","Dom"][d]).join(", "):"Dias específicos"):h.frequency==="weekly"?h.weeklyTarget+"x por semana":"Todos os dias"};
const goal=h=>{h=norm(h);return h.goalValue!==""?h.goalValue+" "+h.goalUnit:(h.goal||"Sem meta definida")};
const scheduled=(h,d)=>{h=norm(h);if(d>today)return false;return h.frequency==="specific"?h.days.includes(d.getDay()||7):true};
const streak=h=>{h=norm(h);let n=0,d=new Date(today),c=new Date(h.createdAt||today);c.setHours(0,0,0,0);while(d>=c){if(scheduled(h,d)){if(h.completions[dateKey(d)])n++;else break}d.setDate(d.getDate()-1)}return n};
function applyTheme(t){document.body.className="";if(t==="paper")document.body.classList.add("theme-paper");if(t==="midnight")document.body.classList.add("theme-midnight")}
function closeAll(){hide($("#habitModal"));hide($("#profileModal"))}
function hide(el){if(el)el.hidden=true} function show(el){if(el)el.hidden=false}
function openHabit(id=null){closeAll();editingId=id;const f=$("#habitForm");f.reset();$("#habitModalLabel").textContent=id?"EDITAR HÁBITO":"NOVO HÁBITO";$("#habitModalTitle").textContent=id?"Ajuste seu hábito":"Que hábito você quer construir?";$("#habitSubmit").textContent=id?"Salvar alterações":"Criar hábito";$("#deleteHabitModal").style.display=id?"block":"none";$("#habitFrequency").value="daily";toggleFrequency();if(id){const raw=data().habits.find(x=>x.id===id);if(!raw)return;const h=norm(raw);$("#habitName").value=h.name;$("#habitCategory").value=h.category;$("#habitIcon").value=h.icon||"☀️";$("#habitTime").value=h.time;$("#habitGoalValue").value=h.goalValue;$("#habitGoalUnit").value=h.goalUnit;$("#habitFrequency").value=h.frequency;$("#weeklyTarget").value=h.weeklyTarget;$$('#specificDaysWrap input').forEach(x=>x.checked=h.days.includes(Number(x.value)));toggleFrequency()}show($("#habitModal"));$("#habitName").focus()}
function closeHabit(){hide($("#habitModal"));editingId=null}
function openProfile(){closeAll();const p=profile();$("#profileName").value=p.name==="Minha rotina"?"":p.name;$("#profileEmail").value=p.email||"";show($("#profileModal"));$("#profileName").focus()}
function closeProfile(){hide($("#profileModal"))}
function toggleFrequency(){const f=$("#habitFrequency")?.value;$("#specificDaysWrap")?.classList.toggle("show",f==="specific");$("#weeklyWrap")?.classList.toggle("show",f==="weekly")}
function showView(v){closeAll();$$(".view").forEach(x=>x.classList.toggle("active-view",x.id===v+"View"));$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));const names={today:["HOJE","Sua rotina","Um dia de cada vez."],calendar:["HISTÓRICO","Calendário","Veja o que você construiu ao longo do tempo."],habits:["SEU SISTEMA","Hábitos","Defina como quer praticar cada hábito."],evolution:["EVOLUÇÃO","Evolução","Consistência, sequência e histórico."],notes:["ESPAÇO PESSOAL","Notas","Ideias, planos, aprendizados e lembretes."],settings:["PREFERÊNCIAS","Configurações","Deixe o app com a sua cara."],account:["PERFIL","Conta","Seu espaço pessoal no Rotina."]};const n=names[v]||names.today;$("#eyebrow").textContent=n[0];$("#pageTitle").textContent=n[1];$("#pageSubtitle").textContent=n[2];$("#addHabitButton").style.display=["today","calendar","habits"].includes(v)?"inline-flex":"none";renderAll()}
function renderToday(){const d=data(),list=d.habits.map(norm).filter(h=>scheduled(h,today)),k=dateKey(today),done=list.filter(h=>h.completions[k]).length,total=list.length,p=total?Math.round(done/total*100):0;$("#todayDate").textContent=today.toLocaleDateString("pt-BR",{day:"numeric",month:"long",year:"numeric"});$("#dailyMessage").textContent=settings().motivation?["Consistência não precisa ser perfeita. Só precisa continuar.","Um pequeno passo hoje já conta.","Seu futuro é construído nas escolhas de hoje.","Faça o que importa, depois repita."][today.getDate()%4]:"Sua rotina de hoje está aqui.";$("#metricHabits").textContent=total;$("#metricDone").textContent=done;$("#metricStreak").textContent=list.length?Math.max(...list.map(streak)):0;$("#habitCount").textContent=total+" "+(total===1?"hábito":"hábitos");$("#progressPercent").textContent=p+"%";$("#progressRing").style.setProperty("--progress",p+"%");const box=$("#habitList");box.innerHTML="";$("#emptyState").classList.toggle("hidden",!!list.length);list.forEach(h=>{const yes=!!h.completions[k],e=document.createElement("article");e.className="habit-card";e.innerHTML=`<div class="habit-icon">${esc(h.icon)}</div><div class="habit-info"><strong>${esc(h.name)}</strong><span>${esc(goal(h))} · <span class="streak">🔥 ${streak(h)} dias</span></span></div><button type="button" class="check ${yes?"done":""}" data-action="today-toggle" data-id="${esc(h.id)}">${yes?"✓":"○"}</button>`;box.appendChild(e)})}
function renderHabits(){const d=data(),box=$("#allHabits");box.innerHTML="";$("#emptyHabits").classList.toggle("hidden",!!d.habits.length);d.habits.map(norm).forEach(h=>{const e=document.createElement("article");e.className="habit-overview";e.innerHTML=`<main><div class="habit-icon">${esc(h.icon)}</div><div><strong>${esc(h.name)}</strong><div class="mini-label">🔥 ${streak(h)} DIAS</div><span class="frequency-badge">${esc(h.category)} · ${esc(freq(h))}</span></div></main><div class="habit-actions"><button class="evolution-button" type="button" data-action="evolution" data-id="${h.id}">Evolução ↗</button><button class="edit-button" type="button" data-action="edit" data-id="${h.id}">Editar</button><button class="delete-button" type="button" data-action="delete" data-id="${h.id}">Excluir</button></div>`;box.appendChild(e)})}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7,d=data();$("#calendarMonthTitle").textContent=month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});const g=document.createElement("div");g.className="calendar-grid";["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].forEach(x=>{const e=document.createElement("div");e.className="weekday";e.textContent=x;g.appendChild(e)});for(let i=0;i<start;i++)g.appendChild(document.createElement("div"));for(let n=1;n<=last.getDate();n++){const dt=new Date(y,m,n),k=dateKey(dt),b=document.createElement("button"),done=d.habits.filter(h=>h.completions?.[k]).length;b.type="button";b.className="calendar-day-btn"+(k===dateKey(today)?" today":"")+(k===dateKey(selectedDate)?" selected":"");b.innerHTML=`<div class="day-number">${n}</div><div class="day-dots">${d.habits.map(h=>`<span class="dot ${h.completions?.[k]?"done":""}"></span>`).join("")}</div>`;b.addEventListener("click",()=>{selectedDate=new Date(dt);renderCalendar()});g.appendChild(b)}$("#calendar").replaceChildren(g);renderSelectedDay()}
function renderSelectedDay(){const d=data(),k=dateKey(selectedDate),done=d.habits.filter(h=>h.completions?.[k]).length,total=d.habits.length,p=total?Math.round(done/total*100):0;$("#selectedDateTitle").textContent=selectedDate.toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"});$("#selectedProgress").textContent=p+"% • "+done+"/"+total;const box=$("#selectedDayHabits");box.innerHTML="";d.habits.map(norm).forEach(h=>{const yes=!!h.completions[k],e=document.createElement("div");e.className="selected-habit";e.innerHTML=`<div class="selected-habit-main"><div class="habit-icon">${esc(h.icon)}</div><div><div class="selected-habit-name">${esc(h.name)}</div><div class="mini-label">${esc(goal(h))}</div></div></div><button type="button" class="check ${yes?"done":""}" data-action="date-toggle" data-id="${h.id}" data-date="${k}">${yes?"✓":"○"}</button>`;box.appendChild(e)})}
function renderEvolution(){const d=data(),raw=d.habits.find(x=>x.id===selectedHabitId)||d.habits[0];if(!raw){$("#evolutionEmpty").classList.remove("hidden");$("#evolutionContent").classList.add("hidden");return}const h=norm(raw),s=stats(h);$("#evolutionEmpty").classList.add("hidden");$("#evolutionContent").classList.remove("hidden");$("#evolutionTitle").textContent=h.name;$("#evolutionName").textContent=h.name;$("#evolutionIcon").textContent=h.icon;$("#evolutionCategory").textContent=h.category.toUpperCase();$("#evolutionSchedule").textContent=[freq(h),h.time?"às "+h.time:"",goal(h)].filter(Boolean).join(" · ");$("#statStreak").textContent=s.current;$("#statBest").textContent=s.best;$("#statRate").textContent=s.rate+"%";$("#statTotal").textContent=s.total;const heat=$("#heatmap");heat.innerHTML="";for(let i=29;i>=0;i--){const dt=new Date(today);dt.setDate(dt.getDate()-i);const c=document.createElement("div");c.className="heat-cell"+(scheduled(h,dt)?" scheduled":"")+(h.completions[dateKey(dt)]?" done":"");heat.appendChild(c)}const rows=[["Frequência",freq(h)],["Horário",h.time||"Sem horário"],["Meta",goal(h)],["Categoria",h.category],["Últimos 30 dias",s.done30+" de "+s.expected],["Criado em",h.createdAt?new Date(h.createdAt).toLocaleDateString("pt-BR"):"—"]];$("#evolutionDetails").innerHTML=rows.map(r=>`<div class="detail-row"><span>${esc(r[0])}</span><strong>${esc(r[1])}</strong></div>`).join("")}
function stats(h){h=norm(h);let total=Object.values(h.completions).filter(Boolean).length,current=0,best=0;let d=new Date(today),created=new Date(h.createdAt||today);created.setHours(0,0,0,0);while(d>=created){if(scheduled(h,d)){if(h.completions[dateKey(d)])current++;else break}d.setDate(d.getDate()-1)}let run=0;for(let x=new Date(created);x<=today;x.setDate(x.getDate()+1)){if(scheduled(h,x)){if(h.completions[dateKey(x)])run++;else run=0;best=Math.max(best,run)}}let expected=0,done30=0;for(let i=0;i<30;i++){let x=new Date(today);x.setDate(x.getDate()-i);if(scheduled(h,x)){expected++;if(h.completions[dateKey(x)])done30++}}return{total,current,best,expected,done30,rate:Math.min(100,Math.round(done30/Math.max(1,expected)*100))}}
function renderNotes(){const items=read(K.notes,[]),canvas=$("#notesCanvas");canvas.querySelectorAll(".note-card").forEach(x=>x.remove());$("#canvasEmpty").classList.toggle("hidden",items.length>0);items.forEach(n=>{const c=document.createElement("article");c.className="note-card "+n.color;c.dataset.id=n.id;c.style.left=n.x+"px";c.style.top=n.y+"px";c.innerHTML=`<span class="note-pin"></span><button class="note-delete" type="button" data-action="delete-note">×</button><textarea maxlength="500" placeholder="Escreva uma ideia...">${esc(n.text)}</textarea>`;canvas.appendChild(c);c.querySelector("textarea").addEventListener("input",e=>{const b=read(K.notes,[]),item=b.find(x=>x.id===n.id);if(item){item.text=e.target.value;write(K.notes,b);$("#notesStatus").textContent="Salvo agora";setTimeout(()=>$("#notesStatus").textContent="Salvo automaticamente",700)}});let drag=false,dx=0,dy=0;c.addEventListener("pointerdown",e=>{if(e.target.tagName==="TEXTAREA"||e.target.closest(".note-delete"))return;drag=true;dx=e.clientX-c.offsetLeft;dy=e.clientY-c.offsetTop;c.setPointerCapture?.(e.pointerId)});c.addEventListener("pointermove",e=>{if(!drag)return;const r=canvas.getBoundingClientRect();c.style.left=Math.max(5,Math.min(e.clientX-r.left-dx,r.width-c.offsetWidth-5))+"px";c.style.top=Math.max(5,Math.min(e.clientY-r.top-dy,r.height-c.offsetHeight-5))+"px"});c.addEventListener("pointerup",()=>{if(!drag)return;drag=false;const b=read(K.notes,[]),item=b.find(x=>x.id===n.id);if(item){item.x=parseInt(c.style.left,10);item.y=parseInt(c.style.top,10);write(K.notes,b)}})})}
function addNote(){const b=read(K.notes,[]),colors=["yellow","peach","green","blue"],n={id:Date.now().toString(),text:"",color:colors[b.length%4],x:50+(b.length%5)*42,y:55+(b.length%4)*38};b.push(n);write(K.notes,b);renderNotes();setTimeout(()=>$("#notesCanvas .note-card:last-child textarea")?.focus(),0)}
function renderSettings(){const s=settings();$("#themeSelect").value=s.theme;$("#motivationToggle").checked=s.motivation;applyTheme(s.theme);$("#supabaseSettingText").textContent=window.SUPABASE_READY?"Supabase configurado. RLS e políticas devem estar definidas no projeto.":"Modo local ativo. Adicione as credenciais publicáveis em supabase-client.js para conectar."}function renderProfile(){const p=profile();$("#profileNameText").textContent=p.name||"Minha rotina";$("#profileEmailText").textContent=p.email||"Perfil local";$("#accountAvatar").textContent=(p.name||"R").trim().charAt(0).toUpperCase()}
function renderAll(){renderToday();renderHabits();renderNotes();renderSettings();renderProfile();if($("#calendarView").classList.contains("active-view"))renderCalendar();if($("#evolutionView").classList.contains("active-view"))renderEvolution()}
function bind(){
 $$(".nav-item").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
 $$("#addHabitButton,[data-open-habit]").forEach(b=>b.addEventListener("click",()=>openHabit()));
 $("#closeHabit").addEventListener("click",closeHabit);$("#closeProfile").addEventListener("click",closeProfile);$("#editProfile").addEventListener("click",openProfile);
 $("#prevMonth").addEventListener("click",()=>{month.setMonth(month.getMonth()-1);selectedDate=new Date(month);renderCalendar()});$("#nextMonth").addEventListener("click",()=>{month.setMonth(month.getMonth()+1);selectedDate=new Date(month);renderCalendar()});
 $("#habitFrequency").addEventListener("change",toggleFrequency);
 $("#habitForm").addEventListener("submit",e=>{e.preventDefault();const d=data(),name=$("#habitName").value.trim(),frequency=$("#habitFrequency").value,days=$$("#specificDaysWrap input:checked").map(x=>Number(x.value));if(!name)return;if(frequency==="specific"&&!days.length){alert("Escolha pelo menos um dia.");return}const base={name,icon:$("#habitIcon").value,category:$("#habitCategory").value.trim()||"Rotina",time:$("#habitTime").value,goalValue:$("#habitGoalValue").value,goalUnit:$("#habitGoalUnit").value,goal:$("#habitGoalValue").value?$("#habitGoalValue").value+" "+$("#habitGoalUnit").value:"",frequency,days,weeklyTarget:Number($("#weeklyTarget").value)||3};if(editingId){const h=d.habits.find(x=>x.id===editingId);if(h)Object.assign(h,base)}else d.habits.push({id:Date.now().toString(),...base,createdAt:new Date().toISOString(),completions:{}});write(K.habits,d);closeHabit();renderAll()});
 $("#deleteHabitModal").addEventListener("click",()=>{if(!editingId)return;if(confirm("Excluir este hábito e todo o histórico?")){const d=data();d.habits=d.habits.filter(x=>x.id!==editingId);write(K.habits,d);closeHabit();renderAll()}});
 $("#profileForm").addEventListener("submit",e=>{e.preventDefault();write(K.profile,{name:$("#profileName").value.trim()||"Minha rotina",email:$("#profileEmail").value.trim()});closeProfile();renderProfile()});
 $("#themeSelect").addEventListener("change",e=>{const s=settings();s.theme=e.target.value;write(K.settings,s);applyTheme(s.theme)});$("#motivationToggle").addEventListener("change",e=>{const s=settings();s.motivation=e.target.checked;write(K.settings,s);renderToday()});
 $("#clearData").addEventListener("click",()=>{if(confirm("Apagar todos os dados deste navegador?")){Object.values(K).forEach(k=>localStorage.removeItem(k));location.reload()}});
 $("#evolutionBack").addEventListener("click",()=>showView("habits"));$("#evolutionEdit").addEventListener("click",()=>selectedHabitId&&openHabit(selectedHabitId));
 $("#noteAddButton").addEventListener("click",addNote);$("#canvasFirstNote").addEventListener("click",addNote);$("#noteClearButton").addEventListener("click",()=>{if(confirm("Limpar todas as notas?")){localStorage.removeItem(K.notes);renderNotes()}});
 document.addEventListener("click",e=>{const el=e.target.closest("[data-action]");if(!el)return;const a=el.dataset.action,id=el.dataset.id;if(a==="today-toggle")toggleHabit(id,dateKey(today));else if(a==="date-toggle")toggleHabit(id,el.dataset.date);else if(a==="edit")openHabit(id);else if(a==="evolution"){selectedHabitId=id;showView("evolution")}else if(a==="delete"){if(confirm("Excluir este hábito e seu histórico?")){const d=data();d.habits=d.habits.filter(x=>x.id!==id);write(K.habits,d);renderAll()}}else if(a==="delete-note"){const card=el.closest(".note-card");saveNotes(read(K.notes,[]).filter(n=>n.id!==card.dataset.id));renderNotes()}});
}
function saveNotes(v){write(K.notes,v)}
window.openHabit=openHabit;window.closeHabit=closeHabit;window.openProfile=openProfile;window.closeProfile=closeProfile;window.showView=showView;window.prevMonth=()=>{};window.nextMonth=()=>{};window.addNote=addNote;window.clearNotes=()=>{};
document.addEventListener("DOMContentLoaded",()=>{bind();applyTheme(settings().theme);showView("today")});
})();