(()=>{
"use strict";
const K={habits:"rotina-v8-habits",notes:"rotina-v8-notes",profile:"rotina-v8-profile",settings:"rotina-v8-settings"};
const S={today:new Date(),month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selectedDate:new Date(),selectedHabitId:null,editingId:null,session:null,channel:null,auth:"login",collapsed:localStorage.getItem("rotina_sidebar")==="1"};
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>Array.from(r.querySelectorAll(q));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const data=()=>read(K.habits,{habits:[]}),notes=()=>read(K.notes,[]),profile=()=>read(K.profile,{name:"Minha rotina",email:""}),settings=()=>read(K.settings,{theme:"obsidian",motivation:true});
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const id=()=>crypto.randomUUID();
const key=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return y+"-"+m+"-"+day};
const icons={sun:"sun",book:"book-2",run:"run",water:"droplet",meditate:"yoga",sleep:"moon",write:"pencil",target:"target",strength:"barbell",brain:"brain",heart:"heart",money:"wallet",walk:"walk",coffee:"coffee",code:"code",read:"book"};
const icon=i=>'<i class="ti ti-'+(icons[i]||i||"target")+'"></i>';
const norm=h=>({...h,icon:h.icon||"sun",category:h.category||"Rotina",time:h.time||"",goalValue:h.goalValue??"",goalUnit:h.goalUnit||"vez",frequency:h.frequency||"daily",days:Array.isArray(h.days)?h.days:[],weeklyTarget:Number(h.weeklyTarget)||3,createdAt:h.createdAt||new Date().toISOString(),completions:h.completions||{}});
const scheduled=(h,d)=>{h=norm(h);if(d>S.today)return false;return h.frequency==="specific"?h.days.includes(d.getDay()||7):true};
const freq=h=>{h=norm(h);if(h.frequency==="specific")return h.days.length?"Dias: "+h.days.map(x=>["","Seg","Ter","Qua","Qui","Sex","Sáb","Dom"][x]).join(", "):"Dias específicos";if(h.frequency==="weekly")return h.weeklyTarget+"x por semana";return"Todos os dias"};
const goal=h=>{h=norm(h);return h.goalValue!==""?h.goalValue+" "+h.goalUnit:"Sem meta"};
const streak=h=>{h=norm(h);let n=0,d=new Date(S.today),c=new Date(h.createdAt);c.setHours(0,0,0,0);while(d>=c){if(scheduled(h,d)){if(h.completions[key(d)])n++;else break}d.setDate(d.getDate()-1)}return n};

function sync(t){if($("#syncStatus"))$("#syncStatus").textContent=t;if($("#supabaseSettingStatus"))$("#supabaseSettingStatus").textContent=t.toUpperCase()}
function theme(){const t=settings().theme;document.body.classList.toggle("theme-midnight",t==="midnight");document.body.classList.toggle("sidebar-collapsed",S.collapsed)}
function closeModal(){const m=$("#globalModal");if(m)m.hidden=true;const c=$("#globalModalContent");if(c)c.replaceChildren();S.editingId=null}
function openModal(node){const c=$("#globalModalContent");c.replaceChildren(node);$("#globalModal").hidden=false}
function modalShell(title,kicker){const frag=document.createDocumentFragment(),e=document.createElement("div");e.innerHTML='<span class="eyebrow">'+esc(kicker)+'</span><h2>'+esc(title)+'</h2>';while(e.firstChild)frag.appendChild(e.firstChild);return frag}
function addField(parent,label,id,type="text",value="",placeholder=""){const l=document.createElement("label");l.textContent=label;const input=document.createElement("input");input.id=id;input.type=type;input.value=value;input.placeholder=placeholder;l.appendChild(input);parent.appendChild(l);return input}
function habitModal(editId=null){
 S.editingId=editId;
 const raw=editId?data().habits.find(x=>x.id===editId):null,h=raw?norm(raw):null;
 const box=document.createElement("div");box.append(...modalShell(editId?"Editar hábito":"Novo hábito",editId?"EDITAR HÁBITO":"NOVO HÁBITO"));
 const form=document.createElement("form");form.id="habitForm";
 addField(form,"Nome","habitName","text",h?.name||"","Ex.: Acordar às 06:30");
 const grid=document.createElement("div");grid.className="form-grid";
 const cat=addField(grid,"Categoria","habitCategory","text",h?.category||"","Saúde");
 const iconLabel=document.createElement("label");iconLabel.textContent="Ícone";const sel=document.createElement("select");sel.id="habitIcon";Object.entries(icons).forEach(([name,cls])=>{const o=document.createElement("option");o.value=name;o.textContent=name;o.selected=(h?.icon||"sun")===name;sel.appendChild(o)});iconLabel.appendChild(sel);grid.appendChild(iconLabel);form.appendChild(grid);
 const grid2=document.createElement("div");grid2.className="form-grid";addField(grid2,"Horário","habitTime","time",h?.time||"");addField(grid2,"Meta","habitGoalValue","number",h?.goalValue??"","1");form.appendChild(grid2);
 const unitLabel=document.createElement("label");unitLabel.textContent="Unidade";const unit=document.createElement("select");unit.id="habitGoalUnit";["vez","vezes","minutos","páginas","copos","km","horas"].forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;o.selected=(h?.goalUnit||"vez")===v;unit.appendChild(o)});unitLabel.appendChild(unit);form.appendChild(unitLabel);
 const freqLabel=document.createElement("label");freqLabel.textContent="Frequência";const fsel=document.createElement("select");fsel.id="habitFrequency";[["daily","Todos os dias"],["specific","Dias específicos"],["weekly","Meta semanal"]].forEach(([v,t])=>{const o=document.createElement("option");o.value=v;o.textContent=t;o.selected=(h?.frequency||"daily")===v;fsel.appendChild(o)});freqLabel.appendChild(fsel);form.appendChild(freqLabel);
 const days=document.createElement("div");days.id="specificDaysWrap";days.className="days-wrap";days.innerHTML='<span class="field-label">Dias da semana</span><div class="day-picker">'+["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map((x,i)=>'<label><input type="checkbox" value="'+(i+1)+'" '+((h?.days||[]).includes(i+1)?"checked":"")+'>'+x+"</label>").join("")+"</div>";form.appendChild(days);
 const weekly=document.createElement("div");weekly.id="weeklyWrap";weekly.className="days-wrap";weekly.innerHTML='<label>Meta semanal<input id="weeklyTarget" type="number" min="1" max="7" value="'+(h?.weeklyTarget||3)+'"></label>';form.appendChild(weekly);
 const foot=document.createElement("div");foot.className="modal-footer";const del=document.createElement("button");del.type="button";del.id="deleteHabitModal";del.className="btn btn-danger";del.textContent="Excluir";del.hidden=!editId;const save=document.createElement("button");save.type="submit";save.className="btn btn-primary";save.textContent=editId?"Salvar alterações":"Criar hábito";foot.append(del,save);form.appendChild(foot);box.appendChild(form);openModal(box);toggleFrequency();$("#habitName").focus()}
function profileModal(){const box=document.createElement("div");box.append(...modalShell("Seu espaço pessoal","PERFIL"));const form=document.createElement("form");form.id="profileForm";const p=profile();addField(form,"Nome","profileName","text",p.name==="Minha rotina"?"":p.name,"Seu nome");addField(form,"E-mail","profileEmail","email",p.email||S.session?.user?.email||"","voce@email.com");const save=document.createElement("button");save.type="submit";save.className="btn btn-primary";save.textContent="Salvar perfil";form.appendChild(save);box.appendChild(form);openModal(box);$("#profileName").focus()}
function toggleFrequency(){const f=$("#habitFrequency")?.value;$("#specificDaysWrap")?.classList.toggle("show",f==="specific");$("#weeklyWrap")?.classList.toggle("show",f==="weekly")}

function renderToday(){const d=data(),k=key(S.today),list=d.habits.map(norm).filter(h=>scheduled(h,S.today)),done=list.filter(h=>h.completions[k]).length,total=list.length,p=total?Math.round(done/total*100):0;$("#todayDate").textContent=S.today.toLocaleDateString("pt-BR",{day:"numeric",month:"long",year:"numeric"});$("#dailyMessage").textContent=settings().motivation?["Consistência não precisa ser perfeita. Só precisa continuar.","Um pequeno passo hoje já conta.","Seu futuro é construído nas escolhas de hoje.","Faça o que importa, depois repita."][S.today.getDate()%4]:"Sua rotina está aqui.";$("#metricHabits").textContent=total;$("#metricDone").textContent=done;$("#metricStreak").textContent=total?Math.max(...list.map(streak)):0;$("#habitCount").textContent=total+" "+(total===1?"hábito":"hábitos");$("#progressPercent").textContent=p+"%";$("#progressRing").style.setProperty("--progress",p+"%");$("#emptyState").classList.toggle("is-hidden",total>0);$("#habitList").innerHTML=list.map(h=>'<article class="habit-card"><div class="habit-icon">'+icon(h.icon)+'</div><div class="habit-info"><strong>'+esc(h.name)+'</strong><span>'+esc(goal(h))+' · <b class="streak">🔥 '+streak(h)+' dias</b></span></div><button class="check '+(h.completions[k]?"done":"")+'" data-action="toggle" data-id="'+h.id+'" type="button">'+(h.completions[k]?'<i class="ti ti-check"></i>':'<i class="ti ti-circle"></i>')+'</button></article>').join("")}
function renderHabits(){const d=data();$("#allHabits").innerHTML=d.habits.map(r=>{const h=norm(r);return'<article class="habit-overview"><main><div class="habit-icon">'+icon(h.icon)+'</div><div><strong>'+esc(h.name)+'</strong><div class="mini-label">🔥 '+streak(h)+' DIAS</div><span class="frequency-badge">'+esc(h.category)+' · '+esc(freq(h))+'</span></div></main><div class="habit-actions"><button data-action="evolution" data-id="'+h.id+'" type="button">Evolução</button><button data-action="edit" data-id="'+h.id+'" type="button">Editar</button><button data-action="delete" data-id="'+h.id+'" type="button">Excluir</button></div></article>'}).join("");$("#emptyHabits").classList.toggle("is-hidden",!!d.habits.length)}
function renderCalendar(){const y=S.month.getFullYear(),m=S.month.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7,d=data();$("#calendarMonthTitle").textContent=S.month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});let html='<div class="calendar-grid">'+["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].map(x=>'<div class="weekday">'+x+"</div>").join("");for(let i=0;i<offset;i++)html+="<div></div>";for(let n=1;n<=last.getDate();n++){const dt=new Date(y,m,n),k=key(dt);html+='<button class="calendar-day-btn '+(k===key(S.today)?"today ":"")+(k===key(S.selectedDate)?"selected":"")+'" data-calendar-date="'+k+'" type="button"><div class="day-number">'+n+'</div><div class="day-dots">'+d.habits.map(h=>'<span class="dot '+(h.completions?.[k]?"done":"")+'"></span>').join("")+"</div></button>"}$("#calendar").innerHTML=html+"</div>";renderSelectedDay()}
function renderSelectedDay(){const d=data(),k=key(S.selectedDate),done=d.habits.filter(h=>h.completions?.[k]).length,total=d.habits.length;$("#selectedDateTitle").textContent=S.selectedDate.toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"});$("#selectedProgress").textContent=(total?Math.round(done/total*100):0)+"% • "+done+"/"+total;$("#selectedDayHabits").innerHTML=d.habits.map(r=>{const h=norm(r),yes=!!h.completions[k];return'<div class="selected-habit"><div class="selected-habit-main"><div class="habit-icon">'+icon(h.icon)+'</div><div><div class="selected-habit-name">'+esc(h.name)+'</div><div class="mini-label">'+esc(goal(h))+'</div></div></div><button class="check '+(yes?"done":"")+'" data-action="date-toggle" data-id="'+h.id+'" data-date="'+k+'" type="button">'+(yes?'<i class="ti ti-check"></i>':'<i class="ti ti-circle"></i>')+"</button></div>"}).join("")}
function renderEvolution(){const d=data(),h=d.habits.map(norm).find(x=>x.id===S.selectedHabitId)||d.habits.map(norm)[0];if(!h){$("#evolutionEmpty").classList.remove("is-hidden");$("#evolutionContent").classList.add("is-hidden");return}S.selectedHabitId=h.id;$("#evolutionEmpty").classList.add("is-hidden");$("#evolutionContent").classList.remove("is-hidden");const total=Object.values(h.completions).filter(Boolean).length,current=streak(h);let best=0,run=0,start=new Date(h.createdAt);for(let x=new Date(start);x<=S.today;x.setDate(x.getDate()+1)){if(scheduled(h,x)){if(h.completions[key(x)])run++;else run=0;best=Math.max(best,run)}}let expected=0,done=0;for(let i=0;i<30;i++){const x=new Date(S.today);x.setDate(x.getDate()-i);if(scheduled(h,x)){expected++;if(h.completions[key(x)])done++}}$("#evolutionTitle").textContent=h.name;$("#evolutionName").textContent=h.name;$("#evolutionIcon").innerHTML=icon(h.icon);$("#evolutionCategory").textContent=h.category.toUpperCase();$("#evolutionSchedule").textContent=[freq(h),h.time?"às "+h.time:"",goal(h)].filter(Boolean).join(" · ");$("#statStreak").textContent=current;$("#statBest").textContent=best;$("#statRate").textContent=Math.min(100,Math.round(done/Math.max(1,expected)*100))+"%";$("#statTotal").textContent=total;$("#heatmap").innerHTML=Array.from({length:30},(_,i)=>{const x=new Date(S.today);x.setDate(x.getDate()-(29-i));return'<div class="heat-cell '+(h.completions[key(x)]?"done":"")+'"></div>'}).join("");$("#evolutionDetails").innerHTML=[["Frequência",freq(h)],["Horário",h.time||"Sem horário"],["Meta",goal(h)],["Categoria",h.category],["Últimos 30 dias",done+" de "+expected],["Criado em",new Date(h.createdAt).toLocaleDateString("pt-BR")]].map(r=>'<div class="detail-row"><span>'+esc(r[0])+'</span><strong>'+esc(r[1])+"</strong></div>").join("")}
function renderNotes(){const arr=notes(),c=$("#notesCanvas");c.querySelectorAll(".note-card").forEach(x=>x.remove());$("#canvasEmpty").classList.toggle("is-hidden",arr.length>0);arr.forEach(n=>{const el=document.createElement("article");el.className="note-card "+(n.color||"yellow");el.dataset.id=n.id;el.style.left=(n.x||30)+"px";el.style.top=(n.y||30)+"px";el.innerHTML='<button class="note-delete" data-action="delete-note" type="button"><i class="ti ti-x"></i></button><textarea maxlength="500" placeholder="Escreva uma ideia...">'+esc(n.text)+'</textarea>';c.appendChild(el);el.querySelector("textarea").addEventListener("input",()=>{const b=notes(),x=b.find(q=>q.id===n.id);if(x){x.text=el.querySelector("textarea").value;write(K.notes,b);clearTimeout(el._t);el._t=setTimeout(()=>remoteNote(x).catch(console.error),450)}});let drag=false,ox=0,oy=0;el.onpointerdown=e=>{if(e.target.tagName==="TEXTAREA"||e.target.closest(".note-delete"))return;drag=true;ox=e.clientX-el.offsetLeft;oy=e.clientY-el.offsetTop;el.setPointerCapture?.(e.pointerId)};el.onpointermove=e=>{if(!drag)return;const r=c.getBoundingClientRect();el.style.left=Math.max(0,Math.min(r.width-el.offsetWidth,e.clientX-r.left-ox))+"px";el.style.top=Math.max(0,Math.min(r.height-el.offsetHeight,e.clientY-r.top-oy))+"px"};el.onpointerup=()=>{if(!drag)return;drag=false;const b=notes(),x=b.find(q=>q.id===n.id);if(x){x.x=parseInt(el.style.left);x.y=parseInt(el.style.top);write(K.notes,b);remoteNote(x).catch(console.error)}}})}
function renderSettings(){const s=settings();$("#themeSelect").value=s.theme;$("#motivationToggle").checked=!!s.motivation;$("#supabaseSettingText").textContent=S.session?"Sincronizado com sua conta.":"Modo local."}
function renderAccount(){const p=profile();$("#profileNameText").textContent=p.name||"Minha rotina";$("#profileEmailText").textContent=p.email||S.session?.user?.email||"—";$("#accountAvatar").innerHTML=icon("sun")}
async function remoteHabit(h){if(!S.session)return;const {error}=await window.supabaseClient.from("habits").upsert({id:h.id,user_id:S.session.user.id,name:h.name,icon:h.icon,category:h.category,time:h.time||null,goal_value:h.goalValue===""?null:Number(h.goalValue),goal_unit:h.goalUnit||null,frequency:h.frequency,days:h.days||[],weekly_target:h.weeklyTarget||3,created_at:h.createdAt,updated_at:new Date().toISOString()},{onConflict:"id"});if(error)throw error}
async function remoteToggle(h,k){if(!S.session)return;if(h.completions[k]){const {error}=await window.supabaseClient.from("habit_completions").upsert({habit_id:h.id,user_id:S.session.user.id,completed_on:k},{onConflict:"habit_id,completed_on"});if(error)throw error}else{const {error}=await window.supabaseClient.from("habit_completions").delete().eq("habit_id",h.id).eq("user_id",S.session.user.id).eq("completed_on",k);if(error)throw error}}
async function remoteDeleteHabit(id){if(!S.session)return;const {error}=await window.supabaseClient.from("habits").delete().eq("id",id).eq("user_id",S.session.user.id);if(error)throw error}
async function remoteNote(n){if(!S.session)return;const {error}=await window.supabaseClient.from("notes").upsert({id:n.id,user_id:S.session.user.id,text:n.text||"",color:n.color||"yellow",x:Math.round(n.x||0),y:Math.round(n.y||0),created_at:n.created_at||new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"id"});if(error)throw error}
async function remoteDeleteNote(id){if(!S.session)return;const {error}=await window.supabaseClient.from("notes").delete().eq("id",id).eq("user_id",S.session.user.id);if(error)throw error}
async function remoteProfile(p){if(!S.session)return;const {error}=await window.supabaseClient.from("profiles").upsert({id:S.session.user.id,display_name:p.name||"Minha rotina",email:p.email||S.session.user.email||null,updated_at:new Date().toISOString()},{onConflict:"id"});if(error)throw error}
async function remoteSettings(s){if(!S.session)return;const {error}=await window.supabaseClient.from("user_settings").upsert({user_id:S.session.user.id,theme:s.theme,motivation:s.motivation,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(error)throw error}
async function migrateLegacy(){if(!S.session)return;const legacy=localStorage.getItem("rotina-v1"),legacyNotes=localStorage.getItem("rotina-notes-board-v1");if(!legacy&&!legacyNotes)return;const q=await window.supabaseClient.from("habits").select("id").eq("user_id",S.session.user.id).limit(1);if(q.data?.length)return;try{if(legacy){const raw=JSON.parse(legacy);for(const old of raw.habits||[]){const h=norm(old);const nh={...h,id:uuid()};await remoteHabit(nh);for(const k of Object.keys(h.completions||{}))if(h.completions[k])await remoteToggle(nh,k)}}if(legacyNotes){const raw=JSON.parse(legacyNotes);for(const n of raw)await remoteNote({...n,id:uuid()})}}catch(e){console.error(e)}}
async function loadCloud(){if(!S.session)return;setSync("Sincronizando");await migrateLegacy();const u=S.session.user.id;const [h,c,n,p,s]=await Promise.all([window.supabaseClient.from("habits").select("*").eq("user_id",u).order("created_at",{ascending:true}),window.supabaseClient.from("habit_completions").select("habit_id,completed_on").eq("user_id",u),window.supabaseClient.from("notes").select("*").eq("user_id",u).order("created_at",{ascending:true}),window.supabaseClient.from("profiles").select("*").eq("id",u).maybeSingle(),window.supabaseClient.from("user_settings").select("*").eq("user_id",u).maybeSingle()]);if(h.error||c.error||n.error)throw(h.error||c.error||n.error);const map={};c.data.forEach(x=>(map[x.habit_id]??=[]).push(x.completed_on));write(K.habits,{habits:h.data.map(x=>({id:x.id,name:x.name,icon:x.icon,category:x.category,time:x.time||"",goalValue:x.goal_value??"",goalUnit:x.goal_unit||"vez",frequency:x.frequency,days:x.days||[],weeklyTarget:x.weekly_target||3,createdAt:x.created_at,completions:Object.fromEntries((map[x.id]||[]).map(k=>[k,true]))}))});write(K.notes,(n.data||[]).map(x=>({id:x.id,text:x.text,color:x.color,x:x.x,y:x.y,created_at:x.created_at})));if(p.data)write(K.profile,{name:p.data.display_name||"Minha rotina",email:p.data.email||S.session.user.email});if(s.data)write(K.settings,{theme:s.data.theme||"obsidian",motivation:s.data.motivation!==false});setSync("Sincronizado")}
function subscribe(){if(!S.session||!window.SUPABASE_READY)return;S.channel?.unsubscribe();S.channel=window.supabaseClient.channel("rotina-"+S.session.user.id).on("postgres_changes",{event:"*",schema:"public",table:"habits",filter:"user_id=eq."+S.session.user.id},()=>loadCloud().then(renderAll).catch(console.error)).on("postgres_changes",{event:"*",schema:"public",table:"habit_completions",filter:"user_id=eq."+S.session.user.id},()=>loadCloud().then(renderAll).catch(console.error)).on("postgres_changes",{event:"*",schema:"public",table:"notes",filter:"user_id=eq."+S.session.user.id},()=>loadCloud().then(renderAll).catch(console.error)).on("postgres_changes",{event:"*",schema:"public",table:"profiles",filter:"id=eq."+S.session.user.id},()=>loadCloud().then(renderAll).catch(console.error)).on("postgres_changes",{event:"*",schema:"public",table:"user_settings",filter:"user_id=eq."+S.session.user.id},()=>loadCloud().then(renderAll).catch(console.error)).subscribe()}

function authMessage(t,type=""){const e=$("#authMessage");if(e){e.textContent=t;e.className="auth-message"+(type?" "+type:"")}}
function setAuthMode(m){S.auth=m;const signup=m==="signup",forgot=m==="forgot";$("#authTitle").textContent=signup?"Crie sua conta":forgot?"Redefina sua senha":"Entre na sua rotina.";$("#authSubtitle").textContent=signup?"Crie seu espaço e sincronize sua evolução.":forgot?"Enviaremos um link para seu e-mail.":"Seus hábitos e progresso sincronizados.";$("#authNameWrap").classList.toggle("is-hidden",!signup);$("#authConfirmWrap").classList.toggle("is-hidden",!signup);$("#authSubmit").textContent=signup?"Criar conta":forgot?"Enviar link":"Entrar";$("#authSwitch").textContent=forgot?"Voltar para entrar":signup?"Já tenho uma conta":"Criar uma conta";$("#forgotPassword").classList.toggle("is-hidden",signup||forgot);$("#resendConfirm").classList.add("is-hidden");$("#authPassword").classList.remove("is-hidden");authMessage("")}
async function authSubmit(){const email=$("#authEmail").value.trim(),password=$("#authPassword").value;if(!email)return authMessage("Informe seu e-mail.","error");$("#authSubmit").disabled=true;authMessage("Aguarde...");try{if(S.auth==="signup"){if(password!==$("#authConfirm").value)throw new Error("As senhas não coincidem.");const {data,error}=await window.supabaseClient.auth.signUp({email,password,options:{data:{display_name:$("#authName").value.trim()||"Minha rotina"},emailRedirectTo:location.origin+location.pathname}});if(error)throw error;if(data.session)return enter(data.session);return authMessage("Conta criada. Confira seu e-mail.","success")}if(S.auth==="forgot"){const {error}=await window.supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;return authMessage("Link enviado para seu e-mail.","success")}const {data,error}=await window.supabaseClient.auth.signInWithPassword({email,password});if(error){if(error.code==="email_not_confirmed"){return ($("#resendConfirm").classList.remove("is-hidden"),authMessage("Confirme seu e-mail antes de entrar.","error"))}throw error}await enter(data.session)}catch(e){authMessage(e.message||"Não foi possível concluir.","error")}finally{$("#authSubmit").disabled=false}}
async function enter(session){S.session=session;$("#authScreen").hidden=true;$("#appShell").hidden=false;document.body.classList.remove("auth-locked");try{await loadCloud();subscribe()}catch(e){console.error(e);setSync("Local")}nav("today")}
function nav(v){$$(".view").forEach(x=>x.classList.toggle("active-view",x.id===v+"View"));$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));if(window.innerWidth<801)$("#sidebar").classList.remove("mobile-open");const t={today:["HOJE","Sua rotina","Um dia de cada vez."],calendar:["HISTÓRICO","Calendário","Veja o que você construiu ao longo do tempo."],habits:["SISTEMA","Hábitos","Frequência, horário, meta e categoria."],evolution:["EVOLUÇÃO","Evolução","Consistência, sequência e histórico."],notes:["ESPAÇO PESSOAL","Notas","Ideias, planos, aprendizados e lembretes."],settings:["PREFERÊNCIAS","Configurações","Defina a experiência do Rotina."],account:["PERFIL","Conta","Seu perfil pessoal."]}[v]||[];$("#eyebrow").textContent=t[0];$("#pageTitle").textContent=t[1];$("#pageSubtitle").textContent=t[2];$("#addHabitButton").hidden=!["today","calendar","habits"].includes(v)}
function action(el){const a=el.dataset.action,id=el.dataset.id;if(a==="new-habit")return habitModal();if(a==="edit-evolution")return habitModal(S.selectedHabitId);if(a==="evolution"){S.selectedHabitId=id;return nav("evolution")}if(a==="edit")return habitModal(id);if(a==="toggle")return toggle(id,key(S.today));if(a==="date-toggle")return toggle(id,el.dataset.date);if(a==="delete")return deleteHabit(id);if(a==="new-note")return addNote();if(a==="delete-note")return deleteNote(el.closest(".note-card")?.dataset.id);if(a==="clear-notes")return clearNotes()}
async function toggle(habitId,k){const d=data(),h=d.habits.find(x=>x.id===habitId);if(!h)return;h.completions=h.completions||{};h.completions[k]=!h.completions[k];if(!h.completions[k])delete h.completions[k];write(K.habits,d);renderAll();setSync("Salvando");try{await remoteToggle(h,k);setSync("Sincronizado")}catch(e){console.error(e);setSync("Erro")}}
async function deleteHabit(habitId){if(!confirm("Excluir este hábito e todo o histórico?"))return;const d=data();d.habits=d.habits.filter(x=>x.id!==habitId);write(K.habits,d);renderAll();try{await remoteDeleteHabit(habitId);setSync("Sincronizado")}catch(e){console.error(e)}}
async function clearNotes(){if(!confirm("Limpar todas as notas?"))return;const ids=notes().map(n=>n.id);write(K.notes,[]);renderNotes();await Promise.all(ids.map(remoteDeleteNote)).catch(console.error)}
function deleteNote(id){if(!id)return;write(K.notes,notes().filter(n=>n.id!==id));renderNotes();remoteDeleteNote(id).catch(console.error)}
async function saveHabit(){const d=data(),name=$("#habitName").value.trim(),frequency=$("#habitFrequency").value,days=$$("#specificDaysWrap input:checked").map(x=>Number(x.value));if(!name)return;if(frequency==="specific"&&!days.length)return alert("Escolha pelo menos um dia.");const base={name,icon:$("#habitIcon").value,category:$("#habitCategory").value.trim()||"Rotina",time:$("#habitTime").value,goalValue:$("#habitGoalValue").value,goalUnit:$("#habitGoalUnit").value,frequency,days,weeklyTarget:Number($("#weeklyTarget").value)||3};let h;if(S.editingId){h=d.habits.find(x=>x.id===S.editingId);if(!h)return;Object.assign(h,base)}else{h={id:uuid(),...base,createdAt:new Date().toISOString(),completions:{}};d.habits.push(h)}write(K.habits,d);closeModal();renderAll();setSync("Salvando");try{await remoteHabit(norm(h));setSync("Sincronizado")}catch(e){console.error(e);setSync("Erro")}}
async function saveProfile(){const p={name:$("#profileName").value.trim()||"Minha rotina",email:$("#profileEmail").value.trim()};write(K.profile,p);closeModal();renderAccount();try{await remoteProfile(p)}catch(e){console.error(e)}}
function installPwa(){if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.error)}
function bind(){
 $("#authForm").addEventListener("submit",e=>{e.preventDefault();authSubmit()});
 $("#authSwitch").addEventListener("click",()=>setAuthMode(S.auth==="signup"?"login":"signup"));
 $("#forgotPassword").addEventListener("click",()=>setAuthMode("forgot"));
 $("#resendConfirm").addEventListener("click",async()=>{const email=$("#authEmail").value.trim();const {error}=await window.supabaseClient.auth.resend({type:"signup",email,options:{emailRedirectTo:location.origin+location.pathname}});authMessage(error?"Não foi possível reenviar.":"Novo e-mail enviado.",error?"error":"success")});
 document.addEventListener("click",e=>{const navBtn=e.target.closest(".nav-item[data-view]");if(navBtn)return nav(navBtn.dataset.view);if(e.target.closest("#brandHome"))return nav("today");if(e.target.closest("#collapseSidebar")){S.collapsed=!S.collapsed;localStorage.setItem("rotina_sidebar",S.collapsed?"1":"0");return applyTheme()};if(e.target.closest("#mobileMenu"))return $("#sidebar").classList.toggle("mobile-open");if(e.target.closest("#addHabitButton"))return habitModal();if(e.target.closest("#globalModalClose"))return closeModal();if(e.target.closest("#editProfile"))return profileModal();if(e.target.closest("#signOut"))return logout();if(e.target.closest("#prevMonth")){S.month.setMonth(S.month.getMonth()-1);return renderCalendar()}if(e.target.closest("#nextMonth")){S.month.setMonth(S.month.getMonth()+1);return renderCalendar()}const d=e.target.closest("[data-calendar-date]");if(d){const p=d.dataset.calendarDate.split("-").map(Number);S.selectedDate=new Date(p[0],p[1]-1,p[2]);return renderCalendar()}if(e.target.closest("#clearData"))return clearLocal();const a=e.target.closest("[data-action]");if(a)return action(a)});
 document.addEventListener("change",async e=>{if(e.target.id==="habitFrequency")return toggleFrequency();if(e.target.id==="themeSelect"){const s=settings();s.theme=e.target.value;write(K.settings,s);applyTheme();await remoteSettings(s).catch(console.error)}if(e.target.id==="motivationToggle"){const s=settings();s.motivation=e.target.checked;write(K.settings,s);renderToday();await remoteSettings(s).catch(console.error)}});
 document.addEventListener("submit",e=>{if(e.target.id==="habitForm"){e.preventDefault();saveHabit()}if(e.target.id==="profileForm"){e.preventDefault();saveProfile()}});
 $("#globalModal").addEventListener("click",e=>{if(e.target===e.currentTarget)closeModal()});
 document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
}
async function logout(){S.channel?.unsubscribe();await window.supabaseClient.auth.signOut({scope:"local"});S.session=null;Object.values(K).forEach(k=>localStorage.removeItem(k));location.reload()}
function clearLocal(){if(confirm("Limpar somente o cache deste navegador?")){localStorage.removeItem(K.habits);localStorage.removeItem(K.notes);location.reload()}}
function boot(){bind();applyTheme();installPwa();window.supabaseClient?.auth?.onAuthStateChange?.((_,session)=>{if(session&&!S.session)enter(session)});if(!window.SUPABASE_READY){$("#authScreen").hidden=false;return}window.supabaseClient.auth.getSession().then(r=>r.data.session?enter(r.data.session):($("#authScreen").hidden=false)).catch(()=>$("#authScreen").hidden=false)}
boot();
})();