const KEY="rotina-v1", today=new Date();let month=new Date(today.getFullYear(),today.getMonth(),1);
const msgs=["Consistência não precisa ser perfeita. Só precisa continuar.","Um pequeno passo hoje já conta para a pessoa que você quer se tornar.","Você não precisa fazer tudo. Só precisa manter o que importa.","Seu futuro é construído nas pequenas escolhas de hoje.","Volte para o caminho. Recomeçar também faz parte."];
const $=s=>document.querySelector(s), data=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{habits:[]}}catch{return{habits:[]}}}, save=d=>localStorage.setItem(KEY,JSON.stringify(d));
const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function streak(h){let n=0,d=new Date(today);while(h.completions?.[key(d)]){n++;d.setDate(d.getDate()-1)}return n}
function renderToday(){let d=data(),k=key(today),done=d.habits.filter(h=>h.completions?.[k]).length,total=d.habits.length,p=total?Math.round(done/total*100):0;$("#greeting").textContent=today.getHours()<12?"BOM DIA":today.getHours()<18?"BOA TARDE":"BOA NOITE";$("#todayDate").textContent=today.toLocaleDateString("pt-BR",{day:"numeric",month:"long",year:"numeric"});$("#dailyMessage").textContent=msgs[today.getDate()%msgs.length];$("#habitCount").textContent=total+" "+(total===1?"hábito":"hábitos");$("#progressPercent").textContent=p+"%";$("#progressRing").style.setProperty("--progress",p+"%");let box=$("#habitList");box.innerHTML="";$("#emptyState").classList.toggle("hidden",!!total);d.habits.forEach(h=>{let e=document.createElement("article");e.className="habit-card";let yes=!!h.completions?.[k];e.innerHTML=`<div class="habit-icon">${h.icon}</div><div class="habit-info"><strong>${esc(h.name)}</strong><span>${esc(h.goal||"Todos os dias")} · <span class="streak">🔥 ${streak(h)} dias</span></span></div><button class="check ${yes?"done":""}">${yes?"✓":"○"}</button>`;e.querySelector(".check").onclick=()=>toggle(h.id);box.appendChild(e)})}
function toggle(id){let d=data(),h=d.habits.find(x=>x.id===id),k=key(today);h.completions=h.completions||{};h.completions[k]=!h.completions[k];if(!h.completions[k])delete h.completions[k];save(d);renderAll()}
function renderHabits(){let d=data(),b=$("#allHabits");b.innerHTML="";$("#emptyHabits").classList.toggle("hidden",!!d.habits.length);d.habits.forEach(h=>{let e=document.createElement("div");e.className="habit-overview";e.innerHTML=`<main><div class="habit-icon">${h.icon}</div><div><strong>${esc(h.name)}</strong><div class="mini-label">🔥 ${streak(h)} DIAS DE SEQUÊNCIA</div></div></main><button class="delete-button">Excluir</button>`;e.querySelector("button").onclick=()=>{if(confirm("Excluir este hábito?")){d.habits=d.habits.filter(x=>x.id!==h.id);save(d);renderAll()}};b.appendChild(e)})}
function renderCalendar(){let y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7,d=data();$("#calendarMonthTitle").textContent=month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});let g=document.createElement("div");g.className="calendar-grid";["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].forEach(x=>{let e=document.createElement("div");e.className="weekday";e.textContent=x;g.appendChild(e)});for(let i=0;i<start;i++)g.appendChild(document.createElement("div"));for(let n=1;n<=last.getDate();n++){let dt=new Date(y,m,n),e=document.createElement("div");e.className="day"+(key(dt)===key(today)?" today":"");e.innerHTML=`<div class="day-number">${n}</div><div class="day-dots">${d.habits.map(h=>`<span class="dot ${h.completions?.[key(dt)]?"done":""}"></span>`).join("")}</div>`;g.appendChild(e)}$("#calendar").innerHTML="";$("#calendar").appendChild(g)}
function renderAll(){renderToday();if($("#calendarView").classList.contains("active-view"))renderCalendar();if($("#habitsView").classList.contains("active-view"))renderHabits()}
function view(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active-view"));$("#"+v+"View").classList.add("active-view");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#pageTitle").textContent=v==="today"?"Sua rotina de hoje":v==="calendar"?"Seu calendário":"Seus hábitos";renderAll()}
function open(){ $("#modalBackdrop").classList.remove("hidden");$("#habitName").focus()}function close(){$("#modalBackdrop").classList.add("hidden");$("#habitForm").reset()}
document.querySelectorAll(".nav-item").forEach(x=>x.onclick=()=>view(x.dataset.view));$("#addHabitButton").onclick=open;$("#emptyAddButton").onclick=open;$("#emptyAddButton2").onclick=open;$("#closeModal").onclick=close;$("#modalBackdrop").onclick=e=>{if(e.target.id==="modalBackdrop")close()};$("#prevMonth").onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()};$("#habitForm").onsubmit=e=>{e.preventDefault();let d=data();d.habits.push({id:Date.now().toString(),name:$("#habitName").value.trim(),icon:$("#habitIcon").value,goal:$("#habitGoal").value.trim(),completions:{}});save(d);close();renderAll()};renderAll();